parameters:
#    first.example.class: Shorty\FirstBundle\Example

    monservice.class: Shorty\FirstBundle\Services

services:
#    first.example:
#        class: %first.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    monservice:
        class: %HashSlugGenerator.class%
        arguments: [@service_id, "plain_value", %parameter%]